# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Bantay"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE"
description = ""
homepage = "http://example.com/"
tags = []
features = []
min_version = "0.115.2"

[author]
  name = "Gil Locaylocay Caley"
  homepage = "https://github.com/kalanggam"

# If porting an existing theme
[original]
  name = ""
  homepage = ""
  repo = ""
