baseURL = 'https://www.kalanggam.com/'
languageCode = 'en-us'
title = 'Kalanggam'
theme = 'bantay'

# `copyright` will render in footer as safe HTML
copyright = '&copy;2023 Gil Locaylocay Caley'
sectionPagesMenu = 'main'

[permalinks]
  [permalinks.page]
    essays = '/essay/:slug/'
    poetry = '/poem/:slug/'

[params]
  mainSections = ['poetry', 'essays']

  # Sidebar
  # `about` will render in sidebar as safe HTML
  [params.sidebar]
    about = """\
      My name's Gil Locaylocay Caley and I do software and game \
      dev. I also write poetry, essays, and stories.\
      """

    # Sidebar links
    [[params.sidebar.links]]
      name = "Mastodon"
      url = "https://tech.lgbt/@kalanggam"
      weight = 1

    [[params.sidebar.links]]
      name = "GitHub"
      url = "https://github.com/kalanggam"
      weight = 1

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true